# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Qontak
description:        Help Center
lang:               id

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:      "qontak-logo.svg"         

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Lasita Khaerani
    title:          Consultant
    avatar:         avatar-sita.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    sita:
      name:         Lasita Khaerani
      title:        Consultant     
      avatar:       avatar-sita.png
    dian:
      name:         Dian Ratri
      title:        Consultant    
      avatar:       avatar-dian.png

# Social icons displayed in footer
social:
    email:          admin@qontak.com
    website:        https://www.qontak.com
    facebook:       https://www.facebook.com/qontakdotcom
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/qontakcrm
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Qontak.com

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
github:
  repository_url: https://github.com/qontak-dev/support